set_property PACKAGE_PIN Y9 [get_ports {dadata[0]}]
set_property PACKAGE_PIN A20 [get_ports {dadata[1]}]
set_property PACKAGE_PIN B19 [get_ports {dadata[2]}]
set_property PACKAGE_PIN B20 [get_ports {dadata[3]}]
set_property PACKAGE_PIN Y17 [get_ports {dadata[4]}]
set_property PACKAGE_PIN U19 [get_ports {dadata[5]}]
set_property PACKAGE_PIN F19 [get_ports {dadata[6]}]
set_property PACKAGE_PIN F20 [get_ports {dadata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dadata[0]}]
set_property PACKAGE_PIN W8 [get_ports {addata[0]}]
set_property PACKAGE_PIN U18 [get_ports {addata[1]}]
set_property PACKAGE_PIN Y19 [get_ports {addata[2]}]
set_property PACKAGE_PIN Y16 [get_ports {addata[3]}]
set_property PACKAGE_PIN W10 [get_ports {addata[4]}]
set_property PACKAGE_PIN V10 [get_ports {addata[5]}]
set_property PACKAGE_PIN V8 [get_ports {addata[6]}]
set_property PACKAGE_PIN U8 [get_ports {addata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addata[0]}]
set_property PACKAGE_PIN W9 [get_ports ad_clk]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN Y8 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN D19 [get_ports rst_n]

create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {addata_IBUF[0]} {addata_IBUF[1]} {addata_IBUF[2]} {addata_IBUF[3]} {addata_IBUF[4]} {addata_IBUF[5]} {addata_IBUF[6]} {addata_IBUF[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {dadata_OBUF[0]} {dadata_OBUF[1]} {dadata_OBUF[2]} {dadata_OBUF[3]} {dadata_OBUF[4]} {dadata_OBUF[5]} {dadata_OBUF[6]} {dadata_OBUF[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets da_clk_OBUF]
